p8105_hw1_qc2336
================
Qiran Chen
2023-09-17

## Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library("moderndive")
data("early_january_weather")
```

``` r
skimr::skim(early_january_weather)
```

|                                                  |                       |
|:-------------------------------------------------|:----------------------|
| Name                                             | early_january_weather |
| Number of rows                                   | 358                   |
| Number of columns                                | 15                    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                       |
| Column type frequency:                           |                       |
| character                                        | 1                     |
| numeric                                          | 13                    |
| POSIXct                                          | 1                     |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                       |
| Group variables                                  | None                  |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| origin        |         0 |             1 |   3 |   3 |     0 |        1 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate |    mean |     sd |      p0 |     p25 |     p50 |     p75 |    p100 | hist  |
|:--------------|----------:|--------------:|--------:|-------:|--------:|--------:|--------:|--------:|--------:|:------|
| year          |         0 |          1.00 | 2013.00 |   0.00 | 2013.00 | 2013.00 | 2013.00 | 2013.00 | 2013.00 | ▁▁▇▁▁ |
| month         |         0 |          1.00 |    1.00 |   0.00 |    1.00 |    1.00 |    1.00 |    1.00 |    1.00 | ▁▁▇▁▁ |
| day           |         0 |          1.00 |    8.04 |   4.31 |    1.00 |    4.00 |    8.00 |   12.00 |   15.00 | ▇▇▇▇▇ |
| hour          |         0 |          1.00 |   11.53 |   6.92 |    0.00 |    6.00 |   11.50 |   17.75 |   23.00 | ▇▇▆▇▇ |
| temp          |         0 |          1.00 |   39.58 |   7.06 |   24.08 |   33.98 |   39.02 |   44.96 |   57.92 | ▃▇▇▇▁ |
| dewp          |         0 |          1.00 |   28.06 |  10.73 |    8.96 |   19.94 |   26.06 |   35.06 |   53.06 | ▃▇▆▂▃ |
| humid         |         0 |          1.00 |   65.48 |  18.95 |   32.86 |   51.34 |   61.67 |   78.68 |  100.00 | ▃▇▆▂▅ |
| wind_dir      |         5 |          0.99 |  208.19 | 115.58 |    0.00 |  140.00 |  240.00 |  290.00 |  360.00 | ▅▁▂▇▆ |
| wind_speed    |         0 |          1.00 |    8.23 |   4.61 |    0.00 |    5.75 |    8.06 |   11.51 |   24.17 | ▅▇▆▂▁ |
| wind_gust     |       308 |          0.14 |   22.53 |   3.63 |   16.11 |   19.56 |   21.86 |   25.32 |   31.07 | ▅▇▃▇▁ |
| precip        |         0 |          1.00 |    0.00 |   0.01 |    0.00 |    0.00 |    0.00 |    0.00 |    0.19 | ▇▁▁▁▁ |
| pressure      |        38 |          0.89 | 1022.52 |   5.57 | 1010.80 | 1018.30 | 1022.05 | 1027.23 | 1034.40 | ▃▇▇▇▃ |
| visib         |         0 |          1.00 |    8.52 |   3.00 |    0.12 |    9.00 |   10.00 |   10.00 |   10.00 | ▁▁▁▁▇ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min                 | max                 | median              | n_unique |
|:--------------|----------:|--------------:|:--------------------|:--------------------|:--------------------|---------:|
| time_hour     |         0 |             1 | 2013-01-01 01:00:00 | 2013-01-15 23:00:00 | 2013-01-08 12:30:00 |      358 |

> The data set consists 15 variables and 358 observations. It describes
> the important characteristics reflecting the weather in January,2013.
> The year,month,day,hour variables details the time when those weather
> data is collected and a variable that combines the four.The mean
> temperature is 39.58 degree. The other important variable are
> humidity, wind direction, speed, gust, precipitation, pressure and
> visibility.

``` r
library(ggplot2)
ggplot(early_january_weather, aes(x=time_hour, y=temp, color=humid))+geom_point()
```

![](p8105_hw1_qc2336_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("p8105_hw1.pdf")
```

    ## Saving 7 x 5 in image

## Problem 2

``` r
df<-tibble(sample=rnorm(n=10,mean=0,sd=1),
               Logical_vector=sample>0,
               Character_vector=c("1","2","3","4","5","6","7","8","9","10"),
               Factor_vector=factor(c(1,0,1,1,1,1,0,2,1,2),levels=c(0,1,2)))
df
```

    ## # A tibble: 10 × 4
    ##     sample Logical_vector Character_vector Factor_vector
    ##      <dbl> <lgl>          <chr>            <fct>        
    ##  1  1.32   TRUE           1                1            
    ##  2 -0.158  FALSE          2                0            
    ##  3  2.24   TRUE           3                1            
    ##  4  1.05   TRUE           4                1            
    ##  5 -0.543  FALSE          5                1            
    ##  6  0.498  TRUE           6                1            
    ##  7  2.08   TRUE           7                0            
    ##  8 -0.0177 FALSE          8                2            
    ##  9 -0.882  FALSE          9                1            
    ## 10  0.320  TRUE           10               2

``` r
mean(pull(df,sample))
```

    ## [1] 0.5900533

``` r
mean(pull(df,Logical_vector))
```

    ## [1] 0.6

``` r
mean(pull(df,Character_vector))
```

    ## Warning in mean.default(pull(df, Character_vector)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(df,Factor_vector))
```

    ## Warning in mean.default(pull(df, Factor_vector)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

> The sample size for normal distribution and the logical vector but not
> for character and factor.

``` r
mean(as.numeric(df$Logical_vector))
```

    ## [1] 0.6

``` r
mean(as.numeric(df$Character_vector))
```

    ## [1] 5.5

``` r
mean(as.numeric(df$Factor_vector))
```

    ## [1] 2

> The vectors now can all be calculated as numbers.
